// src/components/game/Game.vue
<template>
	<div>
		<MobileWarning ref="mobileWarningRef" />
		<template v-if="!isMobile">
			<!-- Loading Screen -->
			<LoadingScreen
				:is-loading="isLoading"
				:loading-progress="loadingProgress"
				:loaded-assets="loadedAssets"
				:total-assets="totalAssets"
			/>

			<!-- Game Content (only show after loading) -->
			<div v-if="!isLoading" style="overflow: hidden; height: 100vh">
				<PreGameScreen
					v-if="!showGame"
					:show-game="showGame"
					@start-game="handleStartGame"
				/>
				<div v-else class="game-container" ref="gameContainer">
					<GameBackground
						:show-cinematics="showCinematics"
						:is-initial-load="isInitialLoad"
						:show-game="showGame"
						:current-sequence="currentSequence"
						:is-transitioning-to-cinematics="isTransitioningToCinematics"
					/>
					<div class="game-content">
						<GameMenu
							:show-cinematics="showCinematics"
							:menu-buttons-ready="menuButtonsReady"
							:is-transitioning-to-cinematics="isTransitioningToCinematics"
							@start-cinematics="handleStartCinematics"
							@show-credits="handleShowCredits"
						/>
						<GameCinematics
							v-if="showCinematics"
							@fade-complete="onFadeComplete"
							@cinematics-complete="onCinematicsComplete"
							@advance-sequence="currentSequence++"
						/>
						<CreditsModal :is-visible="showCredits" @close="showCredits = false" />
					</div>
				</div>
			</div>
		</template>
	</div>
	<audio ref="bgMusic" loop>
		<source src="/assets/music/menu-wow.mp3" type="audio/mpeg" />
	</audio>
	<audio ref="clickSound">
		<source src="/assets/sound/button-press.wav" type="audio/mpeg" />
	</audio>
</template>

<script setup>
	import { ref, onMounted, computed } from 'vue'
	import MobileWarning from './MobileWarning.vue'
	import LoadingScreen from './LoadingScreen.vue'
	import PreGameScreen from './PreGameScreen.vue'
	import GameMenu from './GameMenu.vue'
	import GameCinematics from './GameCinematics.vue'
	import CreditsModal from './CreditsModal.vue'
	import { useAudioManager } from '../../composables/game/useAudioManager'
	import { useGameState } from '../../composables/game/useGameState'
	import { useAssetPreloader } from '../../composables/game/useAssetPreloader'
	import GameBackground from './GameBackground.vue'

	const showCredits = ref(false)
	const gameContainer = ref(null)
	const mobileWarningRef = ref(null)

	const { bgMusic, clickSound, initAudio, playBackgroundMusic, playClickSound } =
		useAudioManager()

	const {
		showGame,
		showCinematics,
		isInitialLoad,
		menuButtonsReady,
		cinematicsComplete,
		isTransitioningToCinematics,
		startGame,
		launchCinematics,
		onCinematicsComplete,
		continueToGame,
		initializeMenu,
	} = useGameState()

	// Get current sequence from cinematics
	const currentSequence = ref(0)

	const {
		isLoading,
		loadingProgress,
		totalAssets,
		loadedAssets,
		preloadAssets,
		isPreloadingComplete,
	} = useAssetPreloader()

	const handleStartGame = async () => {
		startGame()
		await playBackgroundMusic()
	}

	const handleStartCinematics = async () => {
		await launchCinematics(playClickSound)
	}

	const handleShowCredits = async () => {
		await playClickSound()
		showCredits.value = true
	}

	const onFadeComplete = () => {
		// Simplified: just handle the continue to game
		if (cinematicsComplete.value) {
			continueToGame()
		}
	}

	onMounted(async () => {
		// Start preloading assets first
		await preloadAssets()

		// Only initialize audio and menu after assets are loaded
		if (isPreloadingComplete()) {
			initAudio()
			initializeMenu()
		}
	})

	const isMobile = computed(() => mobileWarningRef.value?.isMobile ?? false)
</script>

<style lang="scss" scoped>
	.game-container {
		position: fixed;
		top: 0;
		left: 0;
		width: 100vw;
		height: 100vh;
		display: flex;
		justify-content: center;
		align-items: center;
		z-index: 1000;
		border: none;
		box-shadow: none;
		overflow: hidden;
		overscroll-behavior: none;
		touch-action: none;
		margin: 0;
		padding: 0;
	}

	.game-content {
		position: relative;
		width: 100%;
		height: 100%;
		z-index: 10;
	}
</style>

// src/components/game/Game.tsx
import React, { useState, useRef, useEffect } from 'react'
import MobileWarning from './MobileWarning'
import LoadingScreen from './LoadingScreen'
import PreGameScreen from './PreGameScreen'
import GameBackground from './GameBackground'
import GameMenu from './GameMenu'
import GameCinematics from './GameCinematics'
import CreditsModal from './CreditsModal'
import { useAudioManager } from '../../hooks/game/useAudioManager'
import { useGameState } from '../../hooks/game/useGameState'
import { useAssetPreloader } from '../../hooks/game/useAssetPreloader'
import { useMobileDetection } from '../../hooks/useMobileDetection'

function Game(): React.JSX.Element {
	const [showCredits, setShowCredits] = useState<boolean>(false)
	const [currentSequence, setCurrentSequence] = useState<number>(0)
	const gameContainerRef = useRef<HTMLDivElement>(null)

	const { bgMusic: bgMusicRef, clickSound: clickSoundRef, initAudio, playBackgroundMusic, playClickSound } =
		useAudioManager()

	const {
		showGame,
		showCinematics,
		isInitialLoad,
		menuButtonsReady,
		isTransitioningToCinematics,
		startGame,
		launchCinematics,
		onCinematicsComplete,
		initializeMenu,
	} = useGameState()

	const {
		isLoading,
		loadingProgress,
		totalAssets,
		loadedAssets,
		preloadAssets,
		isPreloadingComplete,
	} = useAssetPreloader()

	const handleStartGame = async (): Promise<void> => {
		startGame()
		await playBackgroundMusic()
	}

	const handleStartCinematics = async (): Promise<void> => {
		await launchCinematics(playClickSound)
	}

	const handleShowCredits = async (): Promise<void> => {
		await playClickSound()
		setShowCredits(true)
	}

	const handleAdvanceSequence = (): void => {
		setCurrentSequence(prev => prev + 1)
	}

	const isMobile = useMobileDetection()

	// Initialize on mount
	useEffect(() => {
		async function initialize(): Promise<void> {
			// Start preloading assets first
			await preloadAssets()

			// Only initialize audio and menu after assets are loaded
			if (isPreloadingComplete()) {
				initAudio()
				initializeMenu()
			} else {
				// If preloading didn't complete, still initialize after a delay
				setTimeout(() => {
					initAudio()
					initializeMenu()
				}, 1000)
			}
		}
		initialize()
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [])

	if (isMobile) {
		return <MobileWarning />
	}

	return (
		<div>
			<LoadingScreen
				isLoading={isLoading}
				loadingProgress={loadingProgress}
				loadedAssets={loadedAssets}
				totalAssets={totalAssets}
			/>

			{!isLoading && (
				<div className="overflow-hidden h-screen">
					{!showGame && <PreGameScreen showGame={showGame} onStartGame={handleStartGame} />}

					{showGame && (
						<div
							className="fixed top-0 left-0 w-screen h-screen flex justify-center items-center z-[1000] border-none shadow-none overflow-hidden overscroll-none touch-none m-0 p-0"
							ref={gameContainerRef}
						>
							<GameBackground
								showCinematics={showCinematics}
								isInitialLoad={isInitialLoad}
								showGame={showGame}
								currentSequence={currentSequence}
								isTransitioningToCinematics={isTransitioningToCinematics}
							/>
							<div className="relative w-full h-full z-10">
								<GameMenu
									showCinematics={showCinematics}
									menuButtonsReady={menuButtonsReady}
									isTransitioningToCinematics={isTransitioningToCinematics}
									onStartCinematics={handleStartCinematics}
									onShowCredits={handleShowCredits}
								/>
								{showCinematics && (
									<GameCinematics
										onCinematicsComplete={onCinematicsComplete}
										onAdvanceSequence={handleAdvanceSequence}
									/>
								)}
								<CreditsModal
									isVisible={showCredits}
									onClose={() => setShowCredits(false)}
								/>
							</div>
						</div>
					)}
				</div>
			)}

			<audio ref={bgMusicRef} loop>
				<source src="/assets/music/menu-wow.mp3" type="audio/mpeg" />
			</audio>
			<audio ref={clickSoundRef}>
				<source src="/assets/sound/button-press.wav" type="audio/mpeg" />
			</audio>
		</div>
	)
}

export default Game
