// src/components/game/GameMenu.vue
<template>
	<div
		class="menu-container"
		:class="{ 'fade-to-black': isTransitioningToCinematics }"
		v-show="!showCinematics"
	>
		<div class="menu-content">
			<h1 class="pixel-title">The<br /><span class="fading-text">Fading</span><br />Crown</h1>
			<div class="menu-buttons">
				<button
					class="pixel-button"
					@click="handleButtonClick('start-cinematics')"
					:disabled="!menuButtonsReady"
				>
					Start Game
				</button>
				<button
					class="pixel-button"
					@click="handleButtonClick('show-credits')"
					:disabled="!menuButtonsReady"
				>
					Credits
				</button>
			</div>
		</div>
	</div>
</template>

<script setup>
	import { inject } from 'vue'
	import { useAudioManager } from '../../composables/game/useAudioManager'

	defineProps({
		showCinematics: {
			type: Boolean,
			required: true,
		},
		menuButtonsReady: {
			type: Boolean,
			required: true,
		},
		isTransitioningToCinematics: {
			type: Boolean,
			required: true,
		},
	})

	const emit = defineEmits(['start-cinematics', 'show-credits'])
	const { playClickSound } = useAudioManager()

	// Get footer visibility to toggle it (same as hide navbar button)
	const _footerVisibility = inject('footerVisibility', {
		toggleFooter: () => {},
	})

	const handleButtonClick = async event => {
		await playClickSound()

		// When starting cinematics, dispatch custom event to hide navbar
		if (event === 'start-cinematics') {
			window.dispatchEvent(new CustomEvent('hide-navbar'))
		}

		emit(event)
	}
</script>

<style lang="scss" scoped>
	.menu-container {
		text-align: center;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		height: 100vh;
		width: 100vw;
		position: relative;
		z-index: 10;
		transition: opacity 2s ease-in-out;

		&.fade-to-black {
			opacity: 0;
		}
	}

	.menu-content {
		display: flex;
		flex-direction: column;
		align-items: flex-start;
		gap: 5vw;
		position: relative;
		right: 17.5vw;
		z-index: 10;
	}

	.pixel-title {
		font-size: 4rem;
		color: $yellow;
		opacity: 0;
		letter-spacing: 15px;
		text-transform: uppercase;
		text-shadow: 5px 5px 5px $black;
		width: 100%;
		font-weight: bold;
		text-align: left;
		animation: titleSlide 5s ease-out 10s forwards;
		position: relative;
		z-index: 10;
	}

	.fading-text {
		animation: FadeAnimation 5s ease-out infinite 5s;
	}

	.menu-buttons {
		display: flex;
		flex-direction: column;
		gap: 1rem;
		opacity: 0;
		animation: simpleFadeIn 5s ease-in 12s forwards;
		width: 60%;
		position: relative;
		z-index: 10;
	}

	.pixel-button {
		font-size: 1.2rem;
		width: 100%;
		color: $yellow;
		background: rgba(0, 0, 0, 0.7);
		border: 3px solid $yellow;
		transition: all 0.3s ease;
		text-transform: uppercase;
		position: relative;
		overflow: hidden;
		border-radius: 10px;

		&:hover {
			background: $yellow;
			color: $black;
			transform: scale(1.1);
		}

		&:active {
			transform: scale(0.95);
		}

		&:disabled {
			opacity: 0;
			cursor: not-allowed;
			pointer-events: none;
			transform: none;
		}
	}

	@keyframes titleSlide {
		0% {
			opacity: 0;
			transform: translateX(-100px);
			letter-spacing: 30px;
		}
		100% {
			opacity: 1;
			transform: translateX(0);
			letter-spacing: 15px;
		}
	}

	@keyframes FadeAnimation {
		0% {
			opacity: 1;
		}
		50% {
			opacity: 0.2;
		}
		100% {
			opacity: 1;
		}
	}

	@keyframes simpleFadeIn {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}

	@media (max-width: 768px) {
		.pixel-title {
			font-size: 2.5rem;
			letter-spacing: 10px;
		}

		.menu-buttons {
			width: 180px;
		}

		.pixel-button {
			font-size: 1.2rem;
			padding: 0.4rem 1.5rem;
		}
	}
</style>

// src/components/game/GameMenu.tsx
import React from 'react'
import { useAudioManager } from '../../hooks/game/useAudioManager'

interface GameMenuProps {
	showCinematics: boolean
	menuButtonsReady: boolean
	isTransitioningToCinematics: boolean
	onStartCinematics: () => void
	onShowCredits: () => void
}

function GameMenu({
	showCinematics,
	menuButtonsReady,
	isTransitioningToCinematics,
	onStartCinematics,
	onShowCredits,
}: GameMenuProps): React.JSX.Element | null {
	const { playClickSound } = useAudioManager()

	const handleButtonClick = async (event: string): Promise<void> => {
		await playClickSound()

		// When starting cinematics, dispatch custom event to hide navbar
		if (event === 'start-cinematics') {
			window.dispatchEvent(new CustomEvent('hide-navbar'))
		}

		if (event === 'start-cinematics') {
			onStartCinematics()
		} else if (event === 'show-credits') {
			onShowCredits()
		}
	}

	if (showCinematics) return null

	return (
		<div
			className={`text-center flex flex-col items-center justify-center h-screen w-screen relative z-10 transition-opacity duration-[2s] ease-in-out ${
				isTransitioningToCinematics ? 'opacity-0' : ''
			}`}
		>
			<div className="flex flex-col items-start gap-[5vw] relative -right-[17.5vw] z-10">
				<h1 className="game-menu-title text-6xl text-yellow opacity-0 tracking-[15px] uppercase drop-shadow-[5px_5px_5px_#000000] w-full font-bold text-left relative z-10 md:text-[2.5rem] md:tracking-[10px]">
					The
					<br />
					<span className="game-menu-fading-text">Fading</span>
					<br />
					Crown
				</h1>
				<div className="game-menu-buttons flex flex-col gap-4 opacity-1 w-[60%] relative z-10 md:w-[180px]">
					<button
						className="text-xl w-full text-yellow bg-black/70 border-3 border-yellow transition-all duration-300 ease-in-out uppercase relative overflow-hidden rounded-[10px] hover:bg-yellow hover:text-black hover:scale-110 disabled:opacity-100 disabled:cursor-not-allowed disabled:pointer-events-none disabled:transform-none active:scale-95 disabled:hover:bg-black/70 disabled:hover:text-yellow disabled:hover:scale-100 md:text-xl md:py-[0.4rem] md:px-6"
						onClick={() => handleButtonClick('start-cinematics')}
						disabled={!menuButtonsReady}
					>
						Start Game
					</button>
					<button
						className="text-xl w-full text-yellow bg-black/70 border-3 border-yellow transition-all duration-300 ease-in-out uppercase relative overflow-hidden rounded-[10px] hover:bg-yellow hover:text-black hover:scale-110 disabled:opacity-100 disabled:cursor-not-allowed disabled:pointer-events-none disabled:transform-none active:scale-95 disabled:hover:bg-black/70 disabled:hover:text-yellow disabled:hover:scale-100 md:text-xl md:py-[0.4rem] md:px-6"
						onClick={() => handleButtonClick('show-credits')}
						disabled={!menuButtonsReady}
					>
						Credits
					</button>
				</div>
			</div>
		</div>
	)
}

export default GameMenu
