// src/components/game/PreGameScreen.vue
<template>
	<div v-if="!showGame" class="pre-game-screen">
		<div class="pre-game-content">
			<h2 class="pre-game-title">
				This game is currently<br />
				<span class="highlight">in development</span>
			</h2>
			<h2 class="pre-game-title">
				For the best experience<br />turn on your
				<span class="highlight">sound</span> before starting
			</h2>
			<button class="pixel-button" @click="$emit('start-game')">Sound is on!</button>
		</div>
	</div>
</template>

<script setup>
defineProps({
	showGame: {
		type: Boolean,
		required: true,
	},
})

defineEmits(['start-game'])
</script>

<style lang="scss" scoped>
	.pre-game-screen {
		display: flex;
		justify-content: center;
		align-items: center;
		z-index: 2000;
		height: 100vh;
		width: 100vw;
	}

	.pre-game-content {
		text-align: center;
		padding: 3rem;
		background: $black;
		border-radius: 15px;
		border: 3px solid $retro-green;
		box-shadow:
			0 0 50px $retro-green,
			inset 0 0 20px rgba(0, 255, 0, 0.1);
		max-width: 100%;
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
	}

	.pre-game-title {
		color: $yellow;
		font-size: 1.2rem;
		margin-bottom: 2rem;
		text-transform: uppercase;
	}

	.highlight {
		color: $retro-green;
		font-weight: bold;
	}

	.pixel-button {
		font-size: 1.2rem;
		width: 50%;
		color: $retro-green;
		background: rgba(0, 0, 0, 0.7);
		border: 3px solid $retro-green;
		transition: all 0.3s ease;
		text-transform: uppercase;
		position: relative;
		overflow: hidden;
		border-radius: 10px;

		&:hover {
			background: $retro-green;
			color: $black;
			transform: scale(1.1);
		}

		&:active {
			transform: scale(0.95);
		}
	}
</style>

// src/components/game/PreGameScreen.tsx
import React from 'react'

interface PreGameScreenProps {
	showGame: boolean
	onStartGame: () => void
}

function PreGameScreen({ showGame, onStartGame }: PreGameScreenProps): React.JSX.Element | null {
	if (showGame) return null

	return (
		<div className="flex justify-center items-center z-[2000] h-screen w-screen">
			<div className="text-center p-12 bg-black rounded-[15px] border-3 border-retro-green shadow-[0_0_50px_#00ff00,inset_0_0_20px_rgba(0,255,0,0.1)] max-w-full absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
				<h2 className="text-yellow text-xl mb-8 uppercase">
					This game is currently
					<br />
					<span className="text-retro-green font-bold">in development</span>
				</h2>
				<h2 className="text-yellow text-xl mb-8 uppercase">
					For the best experience
					<br />
					turn on your
					<span className="text-retro-green font-bold">sound</span> before starting
				</h2>
				<button
					className="text-xl w-1/2 text-retro-green bg-black/70 border-3 border-retro-green transition-all duration-300 ease-in-out uppercase relative overflow-hidden rounded-[10px] hover:bg-retro-green hover:text-black hover:scale-110 active:scale-95"
					onClick={onStartGame}
				>
					Sound is on!
				</button>
			</div>
		</div>
	)
}

export default PreGameScreen
