// src/components/clickCounter.jsx
import { useState, useEffect } from 'react'
import { loadClicks, updateClicks } from '../js/firebase-setup.js'
import './clickCounter.scss'

function ClickCounter() {
	const [counter, setCounter] = useState(null)
	const [loading, setLoading] = useState(true)

	useEffect(() => {
		async function loadCounter() {
			const count = await loadClicks()
			setCounter(count)
			setLoading(false)
		}
		loadCounter()
	}, [])

	const handleIncrementCounter = async () => {
		const newCounter = counter + 1
		setCounter(newCounter)

		try {
			await updateClicks()
		} catch (error) {
			setCounter(counter)
		}
	}

	if (loading) {
		return <p>Loading...</p>
	}

	return (
		<div>
			<div className="nes-container is-dark with-title is-centered is-rounded">
				<p className="title">Waste your time</p>

				<button
					id="clicker"
					className="nes-btn is-normal small-font"
					onClick={handleIncrementCounter}
				>
					ONE CLICK AT A TIME
				</button>

				<p>
					<span>{counter}</span>
				</p>
			</div>
		</div>
	)
}

export default ClickCounter

// src/components/clickCounter.vue
<template>
	<div>
		<p v-if="loading">Loading...</p>

		<div v-else>
			<!-- NES Button inside the container -->
			<div class="nes-container is-dark with-title is-centered is-rounded">
				<p class="title">Waste your time</p>

				<!-- Button for clicking -->
				<button id="clicker" class="nes-btn is-normal small-font" @click="incrementCounter">
					ONE CLICK AT A TIME
				</button>

				<!-- Display the counter -->
				<p>
					<span>{{ counter }}</span>
				</p>
			</div>
		</div>
	</div>
</template>

<script setup>
	import { ref, onMounted } from 'vue'
	import { loadClicks, updateClicks } from '../js/firebase-setup.js'

	const counter = ref(null)
	const loading = ref(true)

	onMounted(async () => {
		counter.value = await loadClicks()
		loading.value = false
	})

	async function incrementCounter() {
		counter.value++

		try {
			await updateClicks()
		} catch {
			counter.value--
		}
	}
</script>

<style lang="scss" scoped>
	.small-font {
		font-size: 1rem !important;
	}

	.nes-container.is-dark {
		background-color: rgba(255, 255, 255, 0.1) !important;
		border: 0.1vh solid $light-gray !important;
		border-radius: 20px !important;
		text-transform: uppercase !important;
	}
</style>
