// src/components/clickCounter.vue
<template>
	<div>
		<p v-if="loading">Loading...</p>

		<div v-else>
			<!-- NES Button inside the container -->
			<div class="nes-container is-dark with-title is-centered is-rounded">
				<p class="title">Waste your time</p>

				<!-- Button for clicking -->
				<button id="clicker" class="nes-btn is-normal small-font" @click="incrementCounter">
					ONE CLICK AT A TIME
				</button>

				<!-- Display the counter -->
				<p><span>{{ counter }}</span></p>
			</div>
		</div>
	</div>
</template>

<script>
import { loadClicks, updateClicks } from '../js/firebase-setup.js';

export default {
  name: 'ClickCounter',
  data() {
	return {
		counter: null,
		loading: true,
		};
	},
async mounted() {
	this.counter = await loadClicks();
	this.loading = false;
	},
	methods: {
		async incrementCounter() {
			this.counter++;

			try {
			await updateClicks();
			} catch (e) {
			this.counter--;
			console.error("Failed to update Firestore:", e);
			}
			},
		},
};
</script>

<style lang="scss" scoped>
.small-font {
  font-size: 1rem !important;
}

.nes-container.is-dark
{
	background-color: $black;
	border: 0.3vh dashed $retro-green;
	border-radius: 20px;
	text-transform: uppercase;
}
</style>

// src/components/ClickCounter.tsx
import React, { useState, useEffect } from 'react'
import { loadClicks, updateClicks } from '../js/firebase-setup'

function ClickCounter(): React.JSX.Element {
	const [counter, setCounter] = useState<number | null>(null)
	const [loading, setLoading] = useState<boolean>(true)

	async function incrementCounter(): Promise<void> {
		if (counter === null) return
		setCounter(prev => (prev === null ? 0 : prev + 1))

		try {
			await updateClicks()
		} catch {
			setCounter(prev => (prev === null ? 0 : prev - 1))
		}
	}

	useEffect(() => {
		async function loadCounter(): Promise<void> {
			const count = await loadClicks()
			setCounter(count)
			setLoading(false)
		}
		loadCounter()
	}, [])

	if (loading) {
		return <p>Loading...</p>
	}

	return (
		<div>
			<div className="nes-container is-dark with-title is-centered is-rounded bg-black/50 border-[0.3vh] border-dashed border-retro-green rounded-[20px] uppercase">
				<p className="title">Waste your time</p>

				<button
					id="clicker"
					className="nes-btn is-normal text-base"
					onClick={incrementCounter}
				>
					ONE CLICK AT A TIME
				</button>

				<p>
					<span>{counter}</span>
				</p>
			</div>
		</div>
	)
}

export default ClickCounter
