// src/components/game/GameBackground.tsx
import React from 'react'

interface GameBackgroundProps {
	showCinematics: boolean
	isInitialLoad: boolean
	showGame: boolean
	isTransitioningToCinematics: boolean
	currentSequence: number
}

function GameBackground({
	showCinematics,
	isInitialLoad,
	showGame,
	isTransitioningToCinematics,
	currentSequence,
}: GameBackgroundProps): React.JSX.Element {
	const getBackgroundImage = (): string => {
		if (showCinematics && currentSequence >= 0 && currentSequence <= 3) {
			const sequenceImages = [
				'/assets/game/landscape/city-looped.gif',
				'/assets/game/landscape/smoke.gif',
				'/assets/game/landscape/forest1.gif',
				'/assets/game/menu-background.gif',
			]
			return sequenceImages[currentSequence]
		}
		return '/assets/game/menu-background.gif'
	}

	const getBackgroundSize = (): string => {
		if (showCinematics && currentSequence >= 0 && currentSequence <= 3) {
			return '100% 100%'
		}
		return isInitialLoad ? '210% auto' : '210% auto'
	}

	const getBackgroundPosition = (): string => {
		if (showCinematics && currentSequence >= 0 && currentSequence <= 3) {
			return '0% 0%'
		}
		return isInitialLoad ? '0% 0%' : '0% 85%'
	}

	const getOpacity = (): number => {
		if (isTransitioningToCinematics) return 0
		if (showCinematics && currentSequence >= 0 && currentSequence <= 3) return 1
		if (showGame) return 1
		if (isInitialLoad) return 0
		return 0
	}

	return (
		<div
			className={`fixed top-0 left-0 w-screen h-screen bg-black z-[1] transition-all duration-[1s] ease-in-out ${
				isInitialLoad ? 'game-background-initial-load' : ''
			}`}
			style={{
				backgroundImage: `url('${getBackgroundImage()}')`,
				backgroundSize: getBackgroundSize(),
				backgroundPosition: getBackgroundPosition(),
				backgroundRepeat: showCinematics && currentSequence >= 0 && currentSequence <= 3 ? 'no-repeat' : 'no-repeat',
				opacity: getOpacity(),
				transition: isTransitioningToCinematics
					? 'opacity 2s ease-in-out'
					: showCinematics && currentSequence >= 0 && currentSequence <= 3
						? 'opacity 8s ease-in-out'
						: 'all 2s ease-in-out',
			}}
		>
			<div className="absolute top-0 left-0 w-full h-full bg-black/15 pointer-events-none z-[2]" />
		</div>
	)
}

export default GameBackground

// src/components/GameBackground.vue
<template>
	<div
		class="game-background"
		:class="{
			'fade-to-black': showCinematics && !shouldMoveBackground && !isFirstSequence,
			'first-message-block': showCinematics && !shouldMoveBackground && isFirstSequence,
			'second-message-block': shouldMoveBackground && !showThirdMessageBlock,
			'third-message-block': showThirdMessageBlock && !showFourthMessageBlock,
			'fourth-message-block': showFourthMessageBlock,
			'initial-load': isInitialLoad,
			'show-game': showGame,
		}"
	>
		<div class="background-overlay"></div>
	</div>
</template>

<script setup>
	import { defineProps } from 'vue'

	defineProps({
		showCinematics: {
			type: Boolean,
			default: false,
		},
		shouldMoveBackground: {
			type: Boolean,
			default: false,
		},
		showThirdMessageBlock: {
			type: Boolean,
			default: false,
		},
		showFourthMessageBlock: {
			type: Boolean,
			default: false,
		},
		isInitialLoad: {
			type: Boolean,
			default: true,
		},
		showGame: {
			type: Boolean,
			default: false,
		},
		isFirstSequence: {
			type: Boolean,
			default: true,
		},
	})
</script>

<style lang="scss" scoped>
	.game-background {
		position: fixed;
		top: 0;
		left: 0;
		width: 100vw;
		height: 100vh;
		background: $black;
		z-index: 1;
		transition: all 1s ease-in-out;

		&::before {
			content: '';
			position: absolute;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
			background-image: url('/assets/game/menu-background.gif');
			background-size: 210% auto;
			background-position: 0% 85%;
			opacity: 0;
			transition: all 2s ease-in-out;
			z-index: 1;
		}

		&.initial-load::before {
			animation: initialFadeIn 10s ease-in forwards;
		}

		&.show-game::before {
			opacity: 1;
		}

		&.fade-to-black::before {
			background-position: 0% 0%;
			opacity: 0;
			transition: all 3s ease-in-out;
		}
		// HERE fix fade to black before castle scroll down + gif size image
		&.first-message-block::before {
			background-image: url('/assets/game/castle.gif');
			background-size: cover;
			background-position: center top;
			opacity: 1;
			z-index: 1;
			transition: opacity 2s ease-in-out;
			animation: castleScrollDown 20s linear forwards;
		}

		&.second-message-block::before {
			background-image: url('/assets/game/dead.gif');
			background-size: 100% 100%;
			background-position: center;
			opacity: 1;
			z-index: 1;
			transition: all 4s ease-in-out;
		}

		&.third-message-block::before {
			background-image: url('/assets/game/mountains.gif');
			background-size: cover;
			background-position: center;
			opacity: 1;
			z-index: 1;
			transition: all 4s ease-in-out;
		}

		&.fourth-message-block::before {
			background-image: url('/assets/game/menu-background.gif');
			background-size: 100% 100%;
			background-position: 0% 0%;
			opacity: 1;
			z-index: 1;
			transition: all 7s ease-in-out;
		}
	}

	.background-overlay {
		position: absolute;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		background: rgba(0, 0, 0, 0.15);
		pointer-events: none;
		z-index: 2;
	}

	@keyframes initialFadeIn {
		from {
			opacity: 0;
			background-size: 210% auto;
			background-position: 0% 0%;
		}
		to {
			opacity: 1;
			background-size: 210% auto;
			background-position: 0% 85%;
		}
	}

	@keyframes castleScrollDown {
		from {
			background-position: center top;
		}
		to {
			background-position: center bottom;
		}
	}
</style>
