// src/components/retroFooter.vue
<template>
	<footer
		class="footer"
		:class="{ 'footer-hidden': !footerVisibility.isVisible.value }"
		data-nosnippet
	>
		<div class="footer-copyright">
			<span>&copy; 2025 Karl Querel - All rights reserved</span>
		</div>
	</footer>
</template>

<script setup>
	import { inject, ref } from 'vue'

	const footerVisibility = inject('footerVisibility', {
		isVisible: ref(true),
		toggleFooter: () => {},
		hideFooter: () => {},
		showFooter: () => {},
	})
</script>

<style lang="scss" scoped>
	.footer {
		background: rgba(0, 0, 0, 0.9);
		border: 0.3vh dashed $retro-green;
		border-bottom: 0;
		border-radius: 20px 20px 0 0;
		position: fixed;
		bottom: 0;
		z-index: 1020;
		width: fit-content;
		min-width: 200px;
		max-width: 90%;
		min-height: 40px;
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 0 1rem;
		box-sizing: border-box;
		transition:
			all 0.3s ease,
			transform 0.5s ease;

		&.footer-hidden {
			transform: translate(0, 100%);
		}
	}

	.footer-copyright {
		font-size: clamp(0.5rem, 2vw, 0.7rem);
		text-align: center;
		color: $white;
		white-space: nowrap;
		padding: 0 0.5rem;
	}

	@media (max-width: 1024px) {
		.footer {
			min-width: 180px;
			max-width: 85%;
			min-height: 35px;
		}
	}

	@media (max-width: 768px) {
		.footer {
			min-width: 160px;
			max-width: 95%;
			min-height: 30px;
			padding: 0 0.5rem;
		}
	}

	@media (max-width: 480px) {
		.footer {
			min-width: 140px;
			max-width: 95%;
			min-height: 25px;
		}
	}
</style>

// src/components/RetroFooter.tsx
import React from 'react'
import { useFooterVisibility } from '../contexts/FooterVisibilityContext'

function RetroFooter(): React.JSX.Element {
	const { isFooterVisible } = useFooterVisibility()

	return (
		<footer
			className={`fixed bottom-0 left-1/2 -translate-x-1/2 z-[1020] w-fit min-w-[200px] max-w-[90%] min-h-[40px] flex items-center justify-center px-4 box-border bg-black/90 border-[0.3vh] border-dashed border-retro-green border-b-0 rounded-t-[20px] transition-all duration-300 ease-in-out ${
				!isFooterVisible ? 'translate-y-full' : ''
			} md:min-w-[180px] md:max-w-[85%] md:min-h-[35px] sm:min-w-[160px] sm:max-w-[95%] sm:min-h-[30px] sm:px-2 xs:min-w-[140px] xs:max-w-[95%] xs:min-h-[25px]`}
			data-nosnippet
		>
			<div className="text-[clamp(0.5rem,2vw,0.7rem)] text-center text-white whitespace-nowrap px-2">
				<span>&copy; 2025 Karl Querel - All rights reserved</span>
			</div>
		</footer>
	)
}

export default RetroFooter
