// src/components/RetroNavbar.tsx
import React, { useState, useEffect, useMemo } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { useFooterVisibility } from '../contexts/FooterVisibilityContext'

function RetroNavbar(): React.JSX.Element {
	const location = useLocation()
	const { toggleFooter } = useFooterVisibility()
	const [isMenuOpen, setIsMenuOpen] = useState<boolean>(false)
	const [isHidden, setIsHidden] = useState<boolean>(false)

	const isGameRoute = useMemo<boolean>(() => location.pathname === '/game', [location.pathname])

	const toggleMenu = (): void => {
		setIsMenuOpen(prev => !prev)
	}

	const closeMenu = (): void => {
		setIsMenuOpen(false)
	}

	const toggleNavbar = (): void => {
		setIsHidden(prev => !prev)
		toggleFooter()
	}

	// Listen for custom hide-navbar event (same as clicking hide button)
	useEffect(() => {
		const handleHideNavbarEvent = (): void => {
			setIsHidden(prev => {
				const newValue = !prev
				toggleFooter()
				return newValue
			})
		}

		window.addEventListener('hide-navbar', handleHideNavbarEvent)

		return () => {
			window.removeEventListener('hide-navbar', handleHideNavbarEvent)
		}
	}, [toggleFooter])

	return (
		<nav
			className={`fixed top-0 left-1/2 -translate-x-1/2 z-[1020] w-[60%] min-h-[60px] h-[10vh] bg-black/90 border-[0.3vh] border-dashed border-retro-green border-t-0 rounded-b-[20px] shadow-[0_2px_4px_rgba(0,0,0,0.3)] transition-all duration-300 ease-in-out ${
				isMenuOpen ? 'border-0 bg-transparent shadow-none' : ''
			} ${isHidden ? '-translate-y-full' : ''} lg:w-[80%] md:w-[95%] sm:w-[95%] xs:w-full`}
		>
			<div className="max-w-full mx-auto h-full flex flex-row items-center justify-between px-8 lg:px-6 md:px-4 sm:px-4 sm:justify-between sm:gap-0 xs:px-2 xs:justify-between">
				<Link
					to="/"
					className="navbar-logo h-full flex items-center relative max-w-[20%] min-w-[40px] md:max-w-[25%] md:h-full md:p-[0.3rem] xs:max-w-[20%] xs:h-full xs:p-[0.2rem]"
					onClick={closeMenu}
				>
					<img
						src="/assets/img/Yako_logo_128.png"
						className="navbar-logo-default w-full h-full object-contain relative rounded-[15%]"
						alt="Logo"
					/>
					<img
						src="/assets/img/Yako_logo_128.png"
						className="navbar-logo-glitch"
						alt="Logo Glitch"
					/>
				</Link>
				<div
					className="hidden lg:hidden md:flex flex-col justify-between w-[35px] h-[21px] z-[1030] relative p-[2px] border-2 border-retro-green rounded-[5px] bg-black/80 shadow-[3px_3px_0_#00ff00] active:translate-x-[2px] active:translate-y-[2px] active:shadow-none xs:w-[25px] xs:h-[18px] xs:p-[1px] xs:border xs:border-retro-green xs:shadow-[2px_2px_0_#00ff00]"
					onClick={toggleMenu}
				>
					<div className="w-full h-[3px] bg-retro-green transition-all duration-300 ease-in-out relative xs:h-[2px]" />
					<div className="w-full h-[3px] bg-retro-green transition-all duration-300 ease-in-out relative xs:h-[2px]" />
					<div className="w-full h-[3px] bg-retro-green transition-all duration-300 ease-in-out relative xs:h-[2px]" />
				</div>
				<ul
					className={`list-none p-0 m-0 hidden lg:flex lg:flex-row lg:gap-12 lg:items-center lg:static lg:opacity-100 lg:visible lg:pointer-events-auto lg:bg-transparent lg:border-0 lg:rounded-none lg:p-0 lg:h-auto lg:w-auto lg:left-auto lg:top-auto lg:translate-x-0 md:fixed md:top-0 md:left-[85%] md:w-[20%] md:h-[90vh] md:bg-black/95 md:flex-col md:justify-end md:gap-8 md:transition-all md:duration-300 md:ease-in-out md:border-l-[0.3vh] md:border-l-dashed md:border-l-retro-green md:border-b-[0.3vh] md:border-b-dashed md:border-b-retro-green md:rounded-bl-[20px] md:p-8 md:opacity-0 md:invisible md:pointer-events-none ${
						isMenuOpen ? 'md:opacity-100 md:visible md:pointer-events-auto' : ''
					} xs:w-[50%] xs:left-[50%]`}
				>
					<li>
						<Link
							to="/game"
							className="glitch-button text-white no-underline transition-all duration-200 ease-in-out relative flex items-center justify-center min-w-[50px] min-h-[50px]"
							data-text="GAME"
							onClick={closeMenu}
						>
							<span className="relative z-[1]">GAME</span>
						</Link>
					</li>
					<li>
						<Link
							to="/under_construction"
							className="glitch-button text-white no-underline transition-all duration-200 ease-in-out relative flex items-center justify-center min-w-[50px] min-h-[50px]"
							data-text="COMING SOON"
							onClick={closeMenu}
						>
							<span className="relative z-[1]">
								COMING
								<br />
								SOON
							</span>
						</Link>
					</li>
					<div className="mt-0 mr-0 flex flex-row gap-8 items-center lg:flex-row lg:mt-0 lg:mr-0 md:mt-8 md:mr-[2vh] md:flex-col">
						<a
							href="mailto:karlquerel@gmail.com"
							target="_blank"
							rel="noreferrer"
							className="scale-125 transition-transform duration-300 ease-in-out hover:scale-150"
						>
							<i className="nes-icon gmail is-medium" />
						</a>
						<a
							href="https://github.com/KarlQuerel"
							target="_blank"
							rel="noreferrer"
							className="scale-125 transition-transform duration-300 ease-in-out hover:scale-150"
						>
							<i className="nes-icon github is-medium" />
						</a>
						<a
							href="https://www.linkedin.com/in/karlquerel"
							target="_blank"
							rel="noreferrer"
							className="scale-125 transition-transform duration-300 ease-in-out hover:scale-150"
						>
							<i className="nes-icon linkedin is-medium" />
						</a>
					</div>
				</ul>
			</div>
			{isGameRoute && (
				<button
					className={`absolute -bottom-[47.5px] left-1/2 -translate-x-1/2 bg-transparent cursor-pointer z-[1020] transition-all duration-300 ease-in-out border-none outline-none p-0 focus:outline-none focus-visible:outline-none active:outline-none focus:border-none focus-visible:border-none active:border-none focus:shadow-none focus-visible:shadow-none active:shadow-none ${
						isHidden ? 'rotate-180' : ''
					} md:hidden`}
					onClick={toggleNavbar}
				>
					<img
						src="/assets/img/navbar-arrow.png"
						alt="Toggle Navbar"
						className={`w-10 h-10 bg-transparent border-2 border-dashed border-retro-green rounded-[10px] transition-transform duration-300 ease-in-out hover:scale-115 hover:shadow-[0_0_8px_#ffbd2e] ${
							isHidden ? 'rotate-180' : ''
						}`}
						style={{
							filter:
								'invert(48%) sepia(79%) saturate(2476%) hue-rotate(86deg) brightness(118%) contrast(119%)',
						}}
					/>
				</button>
			)}
		</nav>
	)
}

export default RetroNavbar

// src/components/retroNavbar.vue
<template>
	<nav class="navbar" :class="{ 'menu-active': isMenuOpen, 'navbar-hidden': isHidden }">
		<div class="navbar-container">
			<router-link to="/" class="logo" @click="closeMenu">
				<img src="/assets/img/Yako_logo_128.png" class="default-img" alt="Logo" />
				<img src="/assets/img/Yako_logo_128.png" class="glitch-img" alt="Logo Glitch" />
			</router-link>
			<div class="menu-toggle" @click="toggleMenu">
				<div class="bar" />
				<div class="bar" />
				<div class="bar" />
			</div>
			<ul class="nav-links" :class="{ active: isMenuOpen }">
				<li>
					<router-link
						to="/game"
						class="glitch-button"
						data-text="GAME"
						@click="closeMenu"
					>
						<span>GAME</span>
					</router-link>
				</li>
				<li>
					<router-link
						to="/under_construction"
						class="glitch-button"
						data-text="COMING SOON"
						@click="closeMenu"
					>
						<span>COMING<br />SOON</span>
					</router-link>
				</li>
				<div class="share">
					<a href="mailto:karlquerel@gmail.com" target="_blank">
						<i class="nes-icon gmail is-medium" />
					</a>
					<a href="https://github.com/KarlQuerel" target="_blank">
						<i class="nes-icon github is-medium" />
					</a>
					<a href="https://www.linkedin.com/in/karlquerel" target="_blank">
						<i class="nes-icon linkedin is-medium" />
					</a>
				</div>
			</ul>
		</div>
		<button
			v-if="isGameRoute"
			class="hide-navbar-btn"
			@click="toggleNavbar"
			:class="{ hidden: isHidden }"
		>
			<img
				src="/assets/img/navbar-arrow.png"
				alt="Toggle Navbar"
				class="arrow-icon"
				:class="{ 'arrow-up': isHidden, 'arrow-down': !isHidden }"
			/>
		</button>
	</nav>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRoute } from 'vue-router'

const route = useRoute()
const isMenuOpen = ref(false)
const isHidden = ref(false)

const isGameRoute = computed(() => route.path === '/game')

const toggleMenu = () => {
	isMenuOpen.value = !isMenuOpen.value
}

const closeMenu = () => {
	isMenuOpen.value = false
}

const toggleNavbar = () => {
	isHidden.value = !isHidden.value
}
</script>

<style lang="scss" scoped>
	.navbar {
		background: rgba(0, 0, 0, 0.9);
		border: 0.3vh dashed $retro-green;
		border-top: 0;
		border-radius: 0 0 20px 20px;
		height: 10vh;
		position: fixed;
		top: 0;
		z-index: 1020;
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
		width: 60%;
		min-height: 60px;
		transition:
			all 0.3s ease,
			transform 0.5s ease;

		&.menu-active {
			border: 0;
			background: transparent;
			box-shadow: none;
		}

		&.navbar-hidden {
			transform: translate(0, -100%);
		}
	}

	.navbar-container {
		max-width: 100%;
		margin: 0 auto;
		height: 100%;
		display: flex;
		flex-direction: row;
		align-items: center;
		justify-content: space-between;
		padding: 0 2rem;
	}

	.logo {
		height: 100%;
		display: flex;
		align-items: center;
		position: relative;
		max-width: 20%;
		min-width: 40px;

		img {
			width: 100%;
			height: 100%;
			object-fit: contain;
			position: relative;
		}

		.default-img {
			position: relative;
			border-radius: 15%;
		}

		.glitch-img {
			opacity: 0;
			border-radius: 15%;
			animation: glitch 2s infinite;
			position: absolute;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
		}

		&:hover {
			.default-img {
				opacity: 0;
			}

			.glitch-img {
				opacity: 1;
			}
		}
	}

	.nav-links {
		list-style: none;
		padding: 0;
		margin: 0;
		display: flex;
		gap: 3rem;
		align-items: center;

		li {
			a {
				color: white;
				text-decoration: none;
				transition: all 0.2s ease;
				position: relative;
				display: flex;
				align-items: center;
				justify-content: center;
				min-width: 50px;
				min-height: 50px;
			}

			// Glitch Effect for Secret
			.glitch-button {
				position: relative;
				transition: all 0.1s ease;

				&::before,
				&::after {
					content: attr(data-text);
					position: absolute;
					top: 0;
					left: 0;
					width: 100%;
					height: 100%;
					background: dark;
					display: flex;
					align-items: center;
					justify-content: center;
					opacity: 0;
					transition: opacity 0.3s ease;
				}

				&::before {
					left: 2px;
					text-shadow: -5px 0 #fffb00;
					animation: glitch-1 2s infinite linear alternate-reverse;
				}

				&::after {
					left: -2px;
					text-shadow: 5px 0 rgb(255, 0, 0);
					animation: glitch-2 3s infinite linear alternate-reverse;
				}

				span {
					position: relative;
					z-index: 1;
				}

				&:hover {
					transform: scale(1.05);
					&::before,
					&::after {
						opacity: 1;
					}
				}
			}
		}
	}

	@keyframes glitch-1 {
		0% {
			transform: translate(0);
		}
		20% {
			transform: translate(-2px, 2px);
		}
		40% {
			transform: translate(-2px, -2px);
		}
		60% {
			transform: translate(2px, 2px);
		}
		80% {
			transform: translate(2px, -2px);
		}
		100% {
			transform: translate(0);
		}
	}

	@keyframes glitch-2 {
		0% {
			clip-path: inset(15% 0 35% 0);
		}
		20% {
			clip-path: inset(55% 0 15% 0);
		}
		40% {
			clip-path: inset(45% 0 45% 0);
		}
		60% {
			clip-path: inset(75% 0 10% 0);
		}
		80% {
			clip-path: inset(15% 0 65% 0);
		}
		100% {
			clip-path: inset(25% 0 25% 0);
		}
	}

	@keyframes glitch {
		0% {
			transform: translate(0) scale(1) rotate(0deg);
		}
		15% {
			transform: translate(-3px, 3px) scale(1.02) rotate(-1deg);
		}
		30% {
			transform: translate(3px, -3px) scale(0.98) rotate(1deg);
		}
		45% {
			transform: translate(-2px, -2px) scale(1.01) rotate(-2deg);
		}
		60% {
			transform: translate(2px, 2px) scale(1.03) rotate(2deg);
		}
		75% {
			transform: translate(-1px, 1px) scale(0.99) rotate(-1deg);
		}
		100% {
			transform: translate(0) scale(1) rotate(0deg);
		}
	}

	@keyframes pixelScan {
		0% {
			opacity: 0.2;
			filter: brightness(1.2);
		}
		50% {
			opacity: 0.4;
			filter: brightness(2);
		}
		100% {
			opacity: 0.2;
			filter: brightness(1.2);
		}
	}

	.menu-toggle {
		display: none;
		flex-direction: column;
		justify-content: space-between;
		width: 35px;
		height: 21px;
		z-index: 1030;
		position: relative;
		padding: 2px;
		border: 2px solid $retro-green;
		border-radius: 5px;
		background: rgba(0, 0, 0, 0.8);
		box-shadow: 3px 3px 0 $retro-green;

		&:active {
			transform: translate(2px, 2px);
			box-shadow: none;
		}

		.bar {
			width: 100%;
			height: 3px;
			background-color: $retro-green;
			transition: all 0.3s ease;
			position: relative;

			&::before,
			&::after {
				content: '';
				position: absolute;
				width: 100%;
				height: 100%;
				background-color: $retro-green;
				opacity: 0;
			}
		}
	}

	.hide-navbar-btn {
		position: absolute;
		bottom: -47.5px;
		background: transparent;
		transform: translateX(-50%);
		cursor: pointer;
		z-index: 1020;
		transition: all 0.3s ease;
		border: none !important;
		outline: none !important;
		padding: 0;

		&:focus,
		&:focus-visible,
		&:active {
			outline: none !important;
			border: none !important;
			box-shadow: none !important;
		}

		&.hidden {
			transform: translateX(-50%) rotate(180deg);
		}

		.arrow-icon {
			width: 40px;
			height: 40px;
			background: transparent;
			border: 2px dashed $retro-green;
			border-radius: 10px;
			transition: transform 0.3s ease;
			filter: invert(48%) sepia(79%) saturate(2476%) hue-rotate(86deg) brightness(118%)
				contrast(119%);

			&:hover {
				transform: scale(1.15);
				box-shadow: 0 0 8px $yellow;
			}
		}
	}

	@media (max-width: 1024px) {
		.navbar {
			width: 80%;
		}

		.navbar-container {
			padding: 0 1.5rem;
		}

		.nav-links {
			gap: 2rem;
		}
	}

	@media (max-width: 768px) {
		.navbar {
			width: 95%;
		}

		.navbar-container {
			padding: 0 1rem;
			justify-content: space-between;
			padding: 0 1rem;
			gap: 0;
		}

		.menu-toggle {
			display: flex;
		}

		.nav-links {
			position: fixed;
			top: 0;
			left: 85%;
			width: 20%;
			height: 90vh;
			background: rgba(0, 0, 0, 0.95);
			flex-direction: column;
			justify-content: flex-end;
			gap: 2rem;
			transition: right 0.3s ease;
			border-left: 0.3vh dashed $retro-green;
			border-bottom: 0.3vh dashed $retro-green;
			border-bottom-left-radius: 20px;
			padding: 2rem;
			opacity: 0;
			visibility: hidden;

			&.active {
				right: 0;
				opacity: 1;
				visibility: visible;
			}

			.share {
				margin-top: 2rem;
				margin-right: 2vh;
				display: flex;
				flex-direction: column;
				gap: 2rem;
				align-items: center;

				a {
					transform: scale(1.2);
					transition: transform 0.3s ease;

					&:hover {
						transform: scale(1.4);
					}
				}
			}
		}

		.logo {
			max-width: 25%;
			height: 100%;
			padding: 0.3rem;

			img {
				height: 100%;
			}
		}

		.hide-navbar-btn {
			display: none;
		}
	}

	@media (max-width: 480px) {
		.navbar {
			width: 100%;
		}

		.navbar-container {
			padding: 0 0.5rem;
			justify-content: space-between;
		}

		.logo {
			max-width: 20%;
			height: 100%;
			padding: 0.2rem;

			img {
				height: 90%;
			}
		}

		.menu-toggle {
			display: flex;
			width: 25px;
			height: 18px;
			padding: 1px;
			border: 1px solid $retro-green;
			box-shadow: 2px 2px 0 $retro-green;

			.bar {
				height: 2px;
			}
		}

		.nav-links {
			width: 50%;
			left: 50%;

			&.active {
				left: 50%;
			}
		}
	}
</style>
