// src/components/underConstruction.jsx
import ClickCounter from './clickCounter'
import './underConstruction.scss'

function UnderConstruction() {
	return (
		<div className="content">
			<div className="nes-container is-dark is-rounded">
				<p>Under Construction</p>
				<img
					src="/assets/img/construction.gif"
					alt="construction GIF"
					className="construction-gif"
				/>
				<p />
			</div>

			<ClickCounter />
		</div>
	)
}

export default UnderConstruction

// src/components/underConstruction.vue
<template>
	<div class="content">
		<div class="nes-container is-dark is-rounded">
			<p>Under Construction</p>
			<img
				src="/assets/img/construction.gif"
				alt="construction GIF"
				class="construction-gif"
			/>
		</div>

		<ClickCounter />
	</div>
</template>

<script setup>
	import ClickCounter from './clickCounter.vue'
</script>

<style lang="scss" scoped>
	.nes-container.is-dark {
		background-color: rgba(255, 255, 255, 0.1) !important;
		border: 0.1vh solid $light-gray !important;
		border-radius: 20px !important;
		margin-bottom: 1rem !important;
		text-transform: uppercase !important;
	}

	.construction-gif {
		max-width: 100%;
		height: auto;
		margin: 0.5rem 0;
		border-radius: 10px;
	}
</style>
