// src/components/UnderConstruction.tsx
import React from 'react'
import ClickCounter from './ClickCounter'

function UnderConstruction(): React.JSX.Element {
	return (
		<div className="content">
			<div className="nes-container is-dark is-rounded bg-black/50 border-[0.3vh] border-dashed border-retro-green rounded-[20px] mb-4 uppercase">
				<p>Under Construction</p>
				<img
					src="/assets/img/construction.gif"
					alt="construction GIF"
					className="max-w-full h-auto my-2 rounded-[10px]"
				/>
				<p />
			</div>

			<ClickCounter />
		</div>
	)
}

export default UnderConstruction

// src/components/underConstruction.vue
<template>
	<div class="content">
		<div class="nes-container is-dark is-rounded">
			<p>Under Construction</p>
			<img
				src="/assets/img/construction.gif"
				alt="construction GIF"
				class="construction-gif"
			/>
			<p />
		</div>

		<!-- Clicker Button -->
		<ClickCounter />
	</div>
</template>

<script>
import ClickCounter from './clickCounter.vue'

export default {
	name: 'UnderConstruction',
	components: {
		ClickCounter,
	},
}
</script>

<style lang="scss" scoped>
	.small-font {
		font-size: 1rem !important;
	}

	.nes-container.is-dark {
		background-color: rgba(0, 0, 0, 0.5);
		border: 0.3vh dashed $retro-green;
		border-radius: 20px;
		margin-bottom: 1rem;
		text-transform: uppercase;
	}

	.construction-gif {
		max-width: 100%;
		height: auto;
		margin: 0.5rem 0;
		border-radius: 10px;
	}
</style>
