// src/App.tsx
import React from 'react'
import RetroNavbar from './components/RetroNavbar'
import RetroFooter from './components/RetroFooter'
import { FooterVisibilityProvider } from './contexts/FooterVisibilityContext'
import { Outlet } from 'react-router-dom'

function App(): React.JSX.Element {
	return (
		<FooterVisibilityProvider>
			<div id="app">
				<RetroNavbar />
				<Outlet />
				<RetroFooter />
			</div>
		</FooterVisibilityProvider>
	)
}

export default App

// src/App.vue
<template>
	<!-- Centralized container -->
	<div id="app">
		<RetroNavbar />
		<router-view />
		<RetroFooter />
	</div>
</template>

<script>
import RetroNavbar from './components/retroNavbar.vue'
import RetroFooter from './components/retroFooter.vue'

export default {
	name: 'App',
	components: {
		RetroNavbar,
		RetroFooter,
	},
}
</script>
